services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"  # HTTP API
      - "6334:6334"  # gRPC (optional)
    volumes:
      - ./qdrant_storage:/qdrant/storage  # Persist data
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped